[conf]
default-lang = "en"

[lang.en]
intro_name = "Malte Klüft"
intro_tagline = "Comp/Sci student striking the balance between author and artist."

[lang.sv]
intro_name = "Malte Klüft"
intro_tagline = "Datavetenskapsstudent som hittar balansen mellan konsult och konstnär."
